#delimit;
/*This is code to extract key-files or support tables. 
Dealer keyfile
 */


/* Part A. PLAN and Category */
clear;

odbc load, exec("select year, dnum, dlr, strt1, strt2, city, st, doi, doc from nefsc_garfo.permit_dealer where year>=2003 order by year;") $oracle_cxn;
destring, replace;


notes: this file was generated by dealer_key_file.do, executed on "`sysdate'";
compress;


save "${my_workdir}/dealer_keyfile_${today_date_string}.dta",replace;

